name: Android CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: prepare project
      env:
        PROJECT: aSPICE
        ANDROID_SDK: $ANDROID_HOME
      run: |
        sudo apt update
        bash eclipse_projects/bVNC/prepare_project.sh $PROJECT ./
    - name: buil with gradle
      run: |
        ./gradlew assembleRelease
        find ./ -name *.apk
